version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - bkimminich
  labels:
  - dependencies
  ignore:
  - dependency-name: express-jwt
    versions:
    - 0.1.3
  - dependency-name: jsonwebtoken
    versions:
    - 0.4.0
  - dependency-name: sanitize-html
    versions:
    - 1.4.2
  - dependency-name: unzipper
    versions:
    - 0.9.15
  - dependency-name: concurrently
    versions:
    - 6.0.0
    - 6.0.1
  - dependency-name: pdfkit
    versions:
    - 0.12.0
  - dependency-name: html-entities
    versions:
    - 2.1.0
    - 2.1.1
    - 2.2.0
    - 2.3.0
    - 2.3.1
  - dependency-name: sinon
    versions:
    - 10.0.0
  - dependency-name: sequelize
    versions:
    - 6.5.0
    - 6.5.1
    - 6.6.0
    - 6.6.1
  - dependency-name: socket.io-client
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.1.3
    - 4.0.0
  - dependency-name: socket.io
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 4.0.0
  - dependency-name: file-type
    versions:
    - 16.2.0
    - 16.3.0
  - dependency-name: sanitize-html
    versions:
    - 2.3.2
  - dependency-name: prom-client
    versions:
    - 13.1.0
- package-ecosystem: npm
  directory: "/frontend"
  schedule:
    interval: daily
    time: "23:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - bkimminich
  labels:
  - dependencies
  ignore:
  - dependency-name: "@angular/cli"
    versions:
    - 11.1.2
    - 11.1.3
    - 11.1.4
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/material"
    versions:
    - 11.2.10
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/compiler"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.11
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/platform-browser"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.11
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/language-service"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.11
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/platform-browser-dynamic"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.11
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: "@angular/router"
    versions:
    - 11.1.1
    - 11.1.2
    - 11.2.0
    - 11.2.1
    - 11.2.10
    - 11.2.11
    - 11.2.2
    - 11.2.3
    - 11.2.4
    - 11.2.5
    - 11.2.6
    - 11.2.7
    - 11.2.8
    - 11.2.9
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: socket.io-client
    versions:
    - 3.1.0
    - 3.1.1
    - 3.1.2
    - 3.1.3
    - 4.0.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: material-icons
    versions:
    - 0.5.3
    - 0.5.4
